# Generated by Django 2.1.7 on 2019-03-13 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Comment')),
                ('author', models.CharField(max_length=15, verbose_name='Author')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('dislikes', models.PositiveIntegerField(default=0, verbose_name='Dislikes')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('author', models.CharField(max_length=15, verbose_name='Author')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('dislikes', models.PositiveIntegerField(default=0, verbose_name='Dislikes')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Name')),
                ('description', models.CharField(max_length=120, verbose_name='Description')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='subreddit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subreddit', to='api.Subreddit'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Post', to='api.Post'),
        ),
    ]
