# Generated by Django 2.1.7 on 2019-03-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190318_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Image URL'),
        ),
    ]
